### ISSUE TITLE
cannot runclient

### ISSUE THREAD

**Issue by neilhuang007** [PianoPenguin471/RavenWeave#18]
`> Task :runClient FAILED
2023-05-29 21:57:41,136 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[21:57:41] [main/INFO]: Extra: []
[21:57:41] [main/INFO]: Found and added coremod: keystrokesmod.client.mixin.MixinLoader
[21:57:41] [main/INFO]: Running with arguments: [--userProperties, {}, --assetsDir, C:/Users/neilhuang007/.gradle/caches/minecraft/assets, --assetIndex, 1.8, --accessToken{REDACTED}, --version, 1.8.9, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[21:57:41] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:57:41] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:57:41] [main/INFO]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[21:57:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:57:41] [main/INFO]: Forge Mod Loader version 11.15.1.2318 for Minecraft 1.8.9 loading
[21:57:41] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_372, running on Windows 10:amd64:10.0, installed at C:\Users\neilhuang007\.jdks\corretto-1.8.0_372\jre
[21:57:41] [main/INFO]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[21:57:41] [main/INFO]: Found a command line coremod : keystrokesmod.client.mixin.MixinLoader
[21:57:41] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/neilhuang007/Documents/GitHub/Raven-bPLUS/libs/mixin-0.8.5.jar Service=LaunchWrapper Env=CLIENT
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: java.lang.NoClassDefFoundError: org/objectweb/asm/commons/ClassRemapper
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.security.AccessController.doPrivileged(Native Method)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at org.spongepowered.asm.mixin.transformer.DefaultExtensions.create(DefaultExtensions.java:54)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.<init>(MixinTransformer.java:116)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at org.spongepowered.asm.mixin.transformer.Proxy.<clinit>(Proxy.java:52)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.lang.Class.newInstance(Class.java:442)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.beginPhase(MixinServiceLaunchWrapper.java:334)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:163)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at org.spongepowered.asm.launch.MixinBootstrap.init(MixinBootstrap.java:128)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at keystrokesmod.client.mixin.MixinLoader.<init>(MixinLoader.java:15)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.lang.Class.newInstance(Class.java:442)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:577)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:244)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
[21:57:41] [main/INFO]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at GradleStart.main(GradleStart.java:26)
[21:57:41] [main/INFO]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.commons.ClassRemapper
[21:57:41] [main/INFO]: [java.lang.Throwable:printStackTrace:635]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
[21:57:41] [main/INFO]: [java.lang.Throwable:printStackTrace:635]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[21:57:41] [main/INFO]: [java.lang.Throwable:printStackTrace:635]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
[21:57:41] [main/INFO]: [java.lang.Throwable:printStackTrace:635]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[21:57:41] [main/INFO]: [java.lang.Throwable:printStackTrace:635]: 	... 44 more
[21:57:41] [main/ERROR]: An error occurred trying to configure the minecraft home at C:\Users\neilhuang007\Documents\GitHub\Raven-bPLUS\run\. for Forge Mod Loader
java.lang.NoClassDefFoundError: org/objectweb/asm/commons/ClassRemapper
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_372]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_372]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_372]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_372]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_372]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_372]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_372]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_372]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_372]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_372]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_372]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_372]
	at org.spongepowered.asm.mixin.transformer.DefaultExtensions.create(DefaultExtensions.java:54) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.<init>(MixinTransformer.java:116) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.Proxy.<clinit>(Proxy.java:52) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_372]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_372]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_372]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_372]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_372]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) ~[launchwrapper-1.12.jar:?]
	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.beginPhase(MixinServiceLaunchWrapper.java:334) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:163) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinBootstrap.init(MixinBootstrap.java:128) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at keystrokesmod.client.mixin.MixinLoader.<init>(MixinLoader.java:15) ~[%5b1.8.9%5d%20BetterKeystrokes%20V-1.2.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_372]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_372]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_372]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_372]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_372]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:577) ~[forgeBin-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:244) ~[forgeBin-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95) [forgeBin-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72) [forgeBin-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forgeBin-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119) [forgeBin-1.8.9-11.15.1.2318-1.8.9.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.commons.ClassRemapper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_372]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_372]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_372]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_372]
	... 44 more
Exception in thread "main" [21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.reflect.InvocationTargetException
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at GradleStart.main(GradleStart.java:26)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/commons/ClassRemapper
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.security.AccessController.doPrivileged(Native Method)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.DefaultExtensions.create(DefaultExtensions.java:54)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.<init>(MixinTransformer.java:116)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.Proxy.<clinit>(Proxy.java:52)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.newInstance(Class.java:442)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.beginPhase(MixinServiceLaunchWrapper.java:334)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:163)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.launch.MixinBootstrap.init(MixinBootstrap.java:128)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at keystrokesmod.client.mixin.MixinLoader.<init>(MixinLoader.java:15)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.newInstance(Class.java:442)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:577)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:244)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:57:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 6 more
[21:57:41] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.commons.ClassRemapper
[21:57:41] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
[21:57:41] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[21:57:41] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
[21:57:41] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[21:57:41] [main/INFO]: [java.lang.Throwable:printStackTrace:644]: 	... 44 more

Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.commons.ClassRemapper

Execution failed for task ':runClient'.
> Process 'command 'C:\Users\neilhuang007\.jdks\corretto-1.8.0_372\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

`
please help

**Comment by Zircta** [comment]
this client is not forge
