### ISSUE TITLE
Reach = crash

### ISSUE THREAD

**Issue by DUELPVP** [PianoPenguin471/RavenWeave#35]
toggle reach with release 1.1.3 will result a crash

**Comment by Sweet-Tooth11** [comment]
I can confirm this crash. Here's a stacktrace:

[2023-07-08 17:30:34.727] [info]  [OUTPUT] [17:30:34] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "ravenweave.client.module.modules.combat.KillAura.isEnabled()" because "ravenweave.client.module.modules.combat.Reach.killAura" is null
	at ravenweave.client.module.modules.combat.Reach.getReach(Reach.java:30) ~[?:?]
	at net.minecraft.client.renderer.EntityRenderer.getMouseOver(EntityRenderer.java:4044) ~[?:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1563) ~[?:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1377) ~[?:?]
	at net.minecraft.client.Minecraft.runGameLoop(SourceFile:915) ~[?:?]
	at net.minecraft.client.Minecraft.run(SourceFile:325) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source) [genesis-0.1.0-SNAPSHOT-all.jar:?]


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Genesis//ravenweave.client.module.modules.combat.Reach.getReach(Reach.java:30)
	at Genesis//net.minecraft.client.renderer.EntityRenderer.getMouseOver(EntityRenderer.java:4044)
	at Genesis//net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1563)

**Comment by Zircta** [comment]
this just doesn't happen to me 😭, but i'll try to fix it

**Comment by Zircta** [comment]
unable to reproduce, if someone can show a video that would be helpful

**Comment by ncwo** [comment]
was it working in earlier versions?
i had the same issue because i was using an outdated version of lunar

what are you using to launch it?

**Comment by Zircta** [comment]
Someone who experiences this crash please provide a video, operating system, and method of launching (e.g. weave manager, lcqt, etc).

**Comment by ncwo** [comment]
[lunarcmd](https://github.com/GameParrot/lunarcmd) is what i was using when i had this issue, but switching to lcqt fixed it

**Comment by god86521** [comment]
the same just happend to me

**Comment by god86521** [comment]
i crashed for turning on reach

**Comment by Cosmic-SC** [comment]
> unable to reproduce, if someone can show a video that would be helpful

easy fix ill do it

**Comment by Cosmic-SC** [comment]
its just a null pointer

**Comment by Zircta** [comment]
Should be fixed in the lastest commit (thanks to [Cosmic-SC](https://github.com/Cosmic-SC)), check out [actions](https://github.com/PianoPenguin471/RavenWeave/actions) for the latest build.

**Comment by DUELPVP** [comment]
Idk how to use it. Please upload a new release

**Comment by Zircta** [comment]
> Idk how to use it. Please upload a new release

Go [here](https://github.com/PianoPenguin471/RavenWeave/actions/runs/5550306207) and click the "compiled" under "Artifacts".
